title: <p align="center"> Vo Minh Khoi </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Ho Chi Minh City, Viet Nam
  <br> (+84) 372111606
  <br> minhkhoivo1502@gmail.com
  <a href="https://www.linkedin.com/in/giorgiocarbone/">LinkedIn</a> |
  <a href="https://github.com/giocoal">GitHub</a>
  </p>


